### ISSUE TITLE
Registration Form

### ISSUE THREAD

**Issue by shahroon** [TechEmblems/shaoor#1]
There will be two ways to register, Web and Mobile for now.

At first we will have following fields for registration,
1> CNIC
2> Full Name
3> Email
4> Device Type
5> Key

**Comment by rqbukhari** [comment]
Completed. UI remaining. Muneeb will do that.

**Comment by rqbukhari** [comment]
Changed Registration form. User will signup with only email and password, After confirmation and login user will be redirected to profile page where user will update rest of the information.
