### ISSUE TITLE
After Login, take user to User section

### ISSUE THREAD

**Issue by shahroon** [TechEmblems/shaoor#5]
Right now after loging in User is landing on the same Home Page. take him/her to the user section. Apply proper header for user section with fancy logout link, user name on right. On left we will have the devices tab and profile section (because we dont have much to display for user right now) so keep the profile section on left as a tab.

**Comment by rqbukhari** [comment]
Fixed, If user login and basic info is incomplete user will be redirected to basic info page otherwise user will be redirected to devices page.
